credentials:
  usernames: 
    melanie:
      email: m.keusch8@gmail.com
      name: Melanie Keusch
      password: $2b$12$8GUskfCcbsBRYTdsGxwG6.fOftHSgTt8XL6s2W8Jp5yga9XomXucG # To be replaced with hashed password
    guest:
      name: Gast
      password: $2b$12$qyTc661dqKWEz/LGwwfGKO.yX/wR/.076g8b7MAMCQDr6Pz1ZuxVy # To be replaced with hashed password
cookie:
  expiry_days: 30  # number of days until password is asked again
  key: JgDyEoKUNItM5prxo194jDeLYzVzmYE6 # Must be string, use https://randomkeygen.com/
  name: streamlitcookie
